src/objects/BatchUpdateP7_CODELIST__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains list of survey codes that are queried for the batchupdateP7 scheduled process.</description>
    <label>BatchUpdateP7_CODELIST</label>
</CustomObject>

src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Survey Description</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <description>Three letter Survey Code</description>
        <externalId>true</externalId>
        <label>Survey Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UHW_Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>UHW Campaign</label>
        <referenceTo>UHW_Campaign__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact Survey Response</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FID__c</fullName>
        <formula>Contact__r.FID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <formula>Survey_Question__r.Survey_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Survey Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Survey Question</description>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Survey Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/UHW_Campaign__c.object
<CustomObject>
    <label>UHW Campaign</label>
    <nameField>
        <label>UHW Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UHW Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ctrlr_mo_test.cls
@isTest
public class ctrlr_mo_test {
    private static Account getTestDataAcct(){    
        // return test account data
        Account em = new Account(name='Test Employer',Account_Group__c='Hospital');
        return em;        
    }
    private static Contact getTestDataContact(){
        //return test contact data
        return new Contact(firstname='Test',lastname='Contact 1',X80_P7_Active__c = false,FID__c='007' );
    }
    private static void setupTestDataSurveyQuestions(){        
        //setup sq (PR1 code for BatchUpdateP7 test)
        UHW_Campaign__c camp = new UHW_Campaign__c();
        insert camp;
        Survey_Question__c sq = new Survey_Question__c(Survey_Code__c = 'PR1',Description__c='test', UHW_Campaign__c=camp.Id);
        insert sq;
        Contact c = getTestDataContact();
        insert c;
        Survey_Response__c sr = new Survey_Response__c(Survey_Question__c = sq.Id,Contact__c = c.Id);
        insert sr;
    }
    static testMethod void TestMOCtrlr(){
        //include test data        
        insert getTestDataAcct();
        //initialize ctrlr class
        ctrlr_mo mo = new ctrlr_mo();
        //use class method for quick and small queries
        List<Contact> lmttwo_cons = ctrlr_mo.getData('Select Id From Contact Limit 2');
        //use class method for larger queries in progression (javascript remoting batch method)
        string hos_query = 'Select Id From Account Where Account_Group__c = \'Hospital\'';
        List<Account> hosptl_emps = ctrlr_mo.getRecords(null,hos_query);
        List<Account> hosptl_emps_withId = ctrlr_mo.getRecords(hosptl_emps[0].Id,hos_query);
    }
    static testMethod void TestP7BatchUpdate(){
        setupTestDataSurveyQuestions();
        insert new BatchUpdateP7_CODELIST__c(Name = 'PR1');
        BatchUpdateP7 dailyActive = new BatchUpdateP7();
        dailyActive.setToActive();
        List<Contact> allCons = new List<Contact>([Select Id, X80_P7_Active__c From Contact]);
        system.debug(allCons);
        BatchUpdateP7.scheduleMe('');
        BatchUpdateP7.scheduleMe('0 0 12 ? * *');
        BatchUpdateP7.scheduleMe('0 0 13 ? * *');
    }

    static testMethod void TestReportCtrlr(){
        ctrlr_rpt80X cr = new ctrlr_rpt80X();
        List<sObject> cons = ctrlr_rpt80X.getRecords(null,'Select Id From Contact Where In_Current_BU__c = true');
        List<sObject> accts = ctrlr_rpt80X.getData('Select Id From Account');        
    }
}