src/objects/Contact_Address__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Addresses</relationshipLabel>
        <relationshipName>Contact_Addresses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FID__c</fullName>
        <formula>Contact__r.FID__c</formula>
        <label>FID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <description>The Zip Code</description>
        <label>PostalCode</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this the Contact&apos;s primary address?  The trigger prevents more than one Primary Address per Contact.</description>
        <label>Primary Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <defaultValue>&quot;CA&quot;</defaultValue>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Contact Address</label>
    <nameField>
        <displayFormat>ADDR-{00000000}</displayFormat>
        <label>Contact Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Contact_Address_DeDupeTest.cls
@isTest(SeeAllData = true)
public class Contact_Address_DeDupeTest {

  public static testMethod void test() {
  
    Account em = new Account(name='Test Employer');
    insert em;
  
    Contact c = new Contact();
    c.lastname = ('TestLast');
    c.firstName = ('TestFirst');
    c.fid__c = '9999-159990001';
    c.account = em;    
    insert c;
    
    Contact_Address__c ca = new Contact_Address__c();
    ca.Contact__c = c.id;
    ca.Street__c = '1234 Elm St.';
    ca.City__c = 'Commerce';    
    ca.State__c = 'CA';
    ca.PostalCode__c = '90022';
    insert ca;

    ca.Primary_Address__c = true;
    update ca;
    
    Contact_Address_DeDupe.cheese();    
   
    System.assert(true);
  }

}