src/objects/EBoardSeats__c.object
<CustomObject>
    <description>All seats of the executive board, including appointee retirees and officers</description>
    <fields>
        <fullName>Executive_Body_Title__c</fullName>
        <formula>TEXT(SeatHolder__r.Executive_Body_Title__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Executive Body Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeatHolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Individual who is seated in this particular (sub seat) of the executive body.  Each individual can occupy one-and-only-one seat at any given time.  Persons who vie for a different position do not lose their current position, but will be unseated before being seated into any position they &quot;win&quot;.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>EBoardSeats</relationshipLabel>
        <relationshipName>EBoardSeats</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EBoardSeats</label>
    <nameField>
        <displayFormat>EBS{00000}</displayFormat>
        <label>EBoardSeatsID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBoardSeats</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EBoardSeatsTrigger_Test.cls
@isTest(SeeAllData =true)
  public class EBoardSeatsTrigger_Test{
  
    public static testMethod void testEBSUpdate(){
    
          Test.startTest();
          EBoardSeats__c eb = [select SeatHolder__c from EBoardSeats__c where SeatHolder__c != null LIMIT 1];
          Id formerId = eb.SeatHolder__c;
          
          eb.SeatHolder__c = null;   //set to null to test that Contact is correctly having its Executive Title cleared.
          Update eb;
          Test.stopTest();
     
          Contact c = [select Executive_Body_Title__c from Contact where Id = :formerId];
          if (c.Executive_Body_Title__c == null)
          {
             System.assert(true);
          }
          else
             System.assert(false);
    }
      
    public static testMethod void testEBSUnseatAll(){
          Test.startTest();
          List<EBoardSeats__c> ebsSeated = [select SeatHolder__c from EBoardSeats__c where SeatHolder__c != null];
           
          for (EBoardSeats__c ebs : ebsSeated)
          {  
                ebs.SeatHolder__c = null;
          }
          update ebsSeated;
          Test.stopTest();
    }      
 }