src/objects/EBoardSeats__c.object
<CustomObject>
    <description>All seats of the executive board, including appointee retirees and officers</description>
    <fields>
        <fullName>Executive_Body_Title__c</fullName>
        <formula>TEXT(SeatHolder__r.Executive_Body_Title__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Executive Body Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeatHolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Individual who is seated in this particular (sub seat) of the executive body.  Each individual can occupy one-and-only-one seat at any given time.  Persons who vie for a different position do not lose their current position, but will be unseated before being seated into any position they &quot;win&quot;.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>EBoardSeats</relationshipLabel>
        <relationshipName>EBoardSeats</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EBoardSeats</label>
    <nameField>
        <displayFormat>EBS{00000}</displayFormat>
        <label>EBoardSeatsID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EBoardSeats</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EBoardSeats_UpdateContact.cls
public class EBoardSeats_UpdateContact
{
    public static void updateContact ( List<EBoardSeats__c> newList, Map<Id, EBoardSeats__c> oldMap, boolean isUpdate)
    {
        if (isUpdate)
        {
            Set<Id> cidSet = new Set<Id>();
            
            for (EBoardSeats__c ebs : newList)
            {
                if (ebs.SeatHolder__c == null && oldMap.get(ebs.Id).SeatHolder__c != null )
                {
                    cidSet.Add(oldMap.get(ebs.Id).SeatHolder__c);
                }
            }
            List<Contact> existingContacts  = [select Id, Executive_Body_Title__c from Contact where Id in :cidSet ];
            
            for (Contact c : existingContacts)
            {
                c.Executive_Body_Title__c = null;
            }
            update existingContacts;
        }
    }
}