src/objects/MCL_Report__c.object
<CustomObject>
    <description>MCL</description>
    <fields>
        <fullName>Add_SOQL_Criteria__c</fullName>
        <description>Additional SOQL Criteria.  For Sys Admins only.</description>
        <label>Add SOQL Criteria</label>
        <length>8192</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bargaining_Units__c</fullName>
        <description>Comma-separated list of selected bargaining units.</description>
        <label>Bargaining Units</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Code_List__c</fullName>
        <description>Codes to ignore responses of</description>
        <label>Code List</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Columns__c</fullName>
        <label>Columns</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Employer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>MCL_Report_Formats</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Filter_Survey_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Filter Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>MCL Reports</relationshipLabel>
        <relationshipName>MCL_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Filter_Survey_Response__c</fullName>
        <label>Filter Survey Response</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Map_Gamma__c</fullName>
        <defaultValue>0.2</defaultValue>
        <label>Map Gamma</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Map_Zoom_Level__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Map Zoom Level</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Orientation__c</fullName>
        <label>Orientation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Portrait</fullName>
                </value>
                <value>
                    <fullName>Landscape</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Page_Size__c</fullName>
        <label>Page Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Letter (8.5x11)</fullName>
                </value>
                <value>
                    <fullName>Legal (8.5x14)</fullName>
                </value>
                <value>
                    <fullName>A4</fullName>
                </value>
                <value>
                    <fullName>Envelope #10</fullName>
                </value>
                <value>
                    <fullName>11x17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prefilter_By_Current_BU__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prefilter By Current BU</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Prefilter_Report_Tags__c</fullName>
        <description>Comma separated list of tags.  If any Contact record contains that tag in that record&apos;s Report Tags field, the Contact record will be included.</description>
        <label>Prefilter Report Tags</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Records_with_no_responses__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only return records that don&apos;t have a survey response for the listed codes</description>
        <label>Ignore Contacts with following SR codes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Row_height__c</fullName>
        <defaultValue>4.0</defaultValue>
        <description>The number of headers that consume the same amount of vertical space as one record.</description>
        <inlineHelpText>The number of headers that consume the same amount of vertical space as one record.</inlineHelpText>
        <label>Row height (in headers)</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rows__c</fullName>
        <inlineHelpText>Maximum number of records to be displayed in one column.</inlineHelpText>
        <label>Rows</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sorting_Config__c</fullName>
        <label>Sorting Config</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>UHW_Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>UHW Campaign</label>
        <referenceTo>UHW_Campaign__c</referenceTo>
        <relationshipName>MCL_Report_Formats</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>MCL Report</label>
    <nameField>
        <label>MCL Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCL Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Survey Description</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>UHW_Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>UHW Campaign</label>
        <referenceTo>UHW_Campaign__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/UHW_Campaign__c.object
<CustomObject>
    <label>UHW Campaign</label>
    <nameField>
        <label>UHW Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UHW Campaigns</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Standard UHW Campaign</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MCLReportCloneExtension.cls
public with sharing class MCLReportCloneExtension {

    private  MCL_Report__c report;

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public MCLReportCloneExtension(ApexPages.StandardController stdController) {
        this.report = (MCL_Report__c)stdController.getRecord();
    }

    public PageReference cloneReport() {
        //Variable to hold the new record
        MCL_Report__c newReport;
        Savepoint sp = Database.setSavepoint();
        try {
            report = [Select Id, Name, Employer__c, Employer__r.Name, Template__c, 
            UHW_Campaign__c, UHW_Campaign__r.Name, Columns__c, Rows__c, 
            Description__c, Orientation__c, Page_Size__c, Bargaining_Units__c,
            Filter_Survey_Question__c, Filter_Survey_Response__c, Sorting_Config__c, Row_Height__c, 
            Filter_Survey_Question__R.Name, Map_Zoom_Level__c, Map_Gamma__c, Add_SOQL_Criteria__c, Code_List__c, Records_with_no_responses__c, 
            Prefilter_By_Current_BU__c, Prefilter_Report_Tags__c             
            from MCL_Report__c where id =:report.id];
            newReport = report.clone(false);
            newReport.Name = newReport.Name + ' - CLONED';
            insert newReport;
            
            List<MCL_Sort_Entry__c> newSortEntries = new List<MCL_Sort_Entry__c>();
            for( MCL_Sort_Entry__c  sortEntry : [SELECT Name, Contact_Field_Name__c, Header__c, 
                MCL_Report__c, Page_Break__c, Sort_Level__c, Sort_Order__c, Survey_Question__c 
                FROM MCL_Sort_Entry__c WHERE MCL_Report__c =:report.id]) {
                 MCL_Sort_Entry__C newSortEntry = sortEntry.clone(false);
                 newSortEntry.MCL_Report__c = newReport.id;
                 newSortEntries.add(newSortEntry);
            }
            insert newSortEntries;
        }
        catch(Exception e) {
            Database.rollback(sp);
            ApexPages.addMessages(e);
            return null;
        }
        return new PageReference('/'+newReport.id);
    }

}