src/objects/MCL_Report__c.object
<CustomObject>
    <description>MCL</description>
    <fields>
        <fullName>Bargaining_Units__c</fullName>
        <description>Comma-separated list of selected bargaining units.</description>
        <label>Bargaining Units</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Code_List__c</fullName>
        <description>Codes to ignore responses of</description>
        <label>Code List</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Columns__c</fullName>
        <label>Columns</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Departments__c</fullName>
        <description>Comma-separated list of selected departments.</description>
        <label>Departments</label>
        <length>8192</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Employer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>MCL_Report_Formats</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Filter_Survey_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Filter Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>MCL Reports</relationshipLabel>
        <relationshipName>MCL_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Filter_Survey_Response__c</fullName>
        <label>Filter Survey Response</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Classes__c</fullName>
        <description>Comma-separated list of selected job classes.</description>
        <label>Job Classes</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Orientation__c</fullName>
        <label>Orientation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Portrait</fullName>
                </value>
                <value>
                    <fullName>Landscape</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Page_Size__c</fullName>
        <label>Page Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Letter (8.5x11)</fullName>
                </value>
                <value>
                    <fullName>Legal (8.5x14)</fullName>
                </value>
                <value>
                    <fullName>A4</fullName>
                </value>
                <value>
                    <fullName>Envelope #10</fullName>
                </value>
                <value>
                    <fullName>11x17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Records_with_no_responses__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only return records that don&apos;t have a survey response for the listed codes</description>
        <label>Ignore Contacts with following SR codes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sorting_Config__c</fullName>
        <label>Sorting Config</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>UHW_Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>UHW Campaign</label>
        <referenceTo>UHW_Campaign__c</referenceTo>
        <relationshipName>MCL_Report_Formats</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>MCL Report</label>
    <nameField>
        <label>MCL Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCL Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Allowed_Responses__c</fullName>
        <defaultValue>&quot;yes&quot;</defaultValue>
        <description>The responses allowed in a Survey Response.  Separate allowed responses by a newline character.</description>
        <label>Allowed Responses</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Survey Description</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <description>Three letter Survey Code</description>
        <externalId>true</externalId>
        <label>Survey Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UHW_Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>UHW Campaign</label>
        <referenceTo>UHW_Campaign__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/UHW_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>UHW Campaign</label>
    <nameField>
        <label>UHW Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UHW Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContactReportConfigControllerExt.cls
global with sharing class ContactReportConfigControllerExt {

    private final MCL_Report__c reportConfig;

    private String templateContents;
    private boolean saveTemplateStatus = true;
    private String saveTemplateError = '';
    private String saveFiltersError = '';

    public ContactReportConfigControllerExt(ApexPages.StandardController stdController) {
        Id recId = stdController.getRecord().Id;
        System.debug('recId = ' + recId);
        this.reportConfig = (MCL_Report__c)[Select Id, Employer__c, Template__c, UHW_Campaign__c, Columns__c, 
         Description__c, Orientation__c, Page_Size__c, Bargaining_Units__c, Job_Classes__c, Departments__c,
         Filter_Survey_Question__c, Filter_Survey_Response__c, Sorting_Config__c, Code_List__c, Records_with_no_responses__c
         from MCL_Report__C where id = :recId];
        this.templateContents = this.reportConfig.Template__c;
    }

    public List<Survey_Question__c> getRelatedSurveyQuestions() {
        Id campaignId = this.reportConfig.UHW_Campaign__c;
        Survey_Question__c[] questions = [SELECT Id, Survey_Code__c, Description__c, Allowed_Responses__c 
            FROM Survey_Question__c 
            WHERE UHW_Campaign__c = :campaignId];
        for (Survey_Question__c q : questions) {
            q.Allowed_Responses__c = q.Allowed_Responses__c.replaceAll('\r\n', ',');
        }
        /*
        and (UHW_Campaign__r.End_date__C = null or UHW_Campaign__r.End_date__C >= TODAY)
        and (UHW_Campaign__r.Start_Date__C = null or UHW_Campaign__r.Start_Date__c <= TODAY)];
        */
        return questions;
    }

    public List<MCL_Sort_Entry__c> getSortFields() {
        return [Select Id, Name, Contact_Field_Name__c, MCL_Report__c,
            Page_Break__c, Header__c, Sort_Order__c, Sort_Level__c, Survey_Question__c 
            from MCL_Sort_Entry__c 
            where MCL_Report__c = :reportConfig.Id order by Sort_Level__c asc];
    }

/*

    public List<String> getAllBargainingUnits() {
        List<String> values = new List<String>();
        values.add('null');
        AggregateResult[] agRes = [Select BU__c from Contact where AccountId = :this.reportConfig.Employer__c GROUP BY BU__c];
        for (AggregateResult res : agRes)  {
            String bu = (String)res.get('BU__c');
            if (bu != null) {
                values.add(bu);
            }
        }
        return values;
    }

    public List<String> getAllJobClasses() {
        List<String> values = new List<String>();
        values.add('null');
        AggregateResult[] agRes = [Select Title from Contact where AccountId = :this.reportConfig.Employer__c GROUP BY Title];
        for (AggregateResult res : agRes)  {
            String title = (String)res.get('Title');
            if (title != null) {
                values.add(title);
            }
        }
        return values;
    }

    public List<String> getAllDepartments() {
        List<String> values = new List<String>();
        values.add('null');
        AggregateResult[] agRes = [Select Department from Contact where AccountId = :this.reportConfig.Employer__c GROUP BY Department];
        for (AggregateResult res : agRes)  {
            String dept = (String)res.get('Department');
            if (dept != null) {
                values.add(dept);
            }
        }
        return values;
    }

*/

/*
    public List<SelectOption> getBargainingUnitOptions() {
        Id accountId = this.reportConfig.Employer__c;
        List<SelectOption> values = new List<SelectOption>();
        AggregateResult[] agRes = [Select BU__c from Contact where AccountId = :accountId GROUP BY BU__c];
        for (AggregateResult res : agRes)  {
            String bu = (String)res.get('BU__c');
            if (bu != null) {
                values.add(new SelectOption(bu, bu));
            }
        }
        System.debug('returning ' + values.size() + ' bargaining unit options');
        return values;
    }

    public List<SelectOption> getJobClassOptions() {
        Id accountId = this.reportConfig.Employer__c;
        List<SelectOption> values = new List<SelectOption>();
        AggregateResult[] agRes = [Select Title from Contact where AccountId = :accountId GROUP BY Title];
        for (AggregateResult res : agRes)  {
            String title = (String)res.get('Title');
            if (title != null) {
                values.add(new SelectOption(title, title));
            }
        }
        return values;
    }

    public List<SelectOption> getDepartmentOptions() {
        Id accountId = this.reportConfig.Employer__c;
        List<SelectOption> values = new List<SelectOption>();
        AggregateResult[] agRes = [Select Department from Contact where AccountId = :accountId GROUP BY Department];
        for (AggregateResult res : agRes)  {
            String dept = (String)res.get('Department');
            if (dept != null) {
                values.add(new SelectOption(dept, dept));
            }
        }
        return values;
    }

    public void setSelectedBargainingUnits(String[] buList) {
        this.selectedBargainingUnits = buList;
    }
    public String[] getSelectedBargainingUnits() {
        return this.selectedBargainingUnits;
    }

    public void setSelectedJobClasses(String[] jcList) {
        this.selectedJobClasses = jcList;
    }
    public String[] getSelectedJobClasses() {
        return this.selectedJobClasses;
    }

    public void setSelectedDepartments(String[] deptList) {
        this.selectedDepartments = deptList;
    }
    public String[] getSelectedDepartments() {
        return this.selectedDepartments;
    }
    */

    public MCL_Report__c getReportConfig() {
        return this.reportConfig;
    }

    /**
    * Save report filter configuration.
    * Called via <apex:actionFunction> tag in VF page
    */
    public PageReference saveFilters() {
        this.reportConfig.Bargaining_Units__c = Apexpages.currentPage().getParameters().get('selectedBargainingUnits');
        this.reportConfig.Job_Classes__c = Apexpages.currentPage().getParameters().get('selectedJobClasses');
        this.reportConfig.Departments__c = Apexpages.currentPage().getParameters().get('selectedDepartments');
        String questionId = Apexpages.currentPage().getParameters().get('filterSurveyQuestion');
        String response = Apexpages.currentPage().getParameters().get('filterSurveyResponse');
        this.reportConfig.Filter_Survey_Question__c = questionId == null || questionId.equals('') ? null : questionId;
        this.reportConfig.Filter_Survey_Response__c = response == null || response.equals('') ? null : response;
        try {
            update this.reportConfig;
            saveFiltersError = '';
        } catch (Exception e) {
            this.saveFiltersError = e.getMessage();
        }
        return null;
    }

    public String getSaveFiltersError() {
        return this.saveFiltersError;
    }
    public String getTemplateContents() {
        return this.templateContents;
    }
    public void setTemplateContents(String contents) {
        this.templateContents = contents;
    }
    public boolean getSaveTemplateStatus() {
        return this.saveTemplateStatus;
    }
    public void setSaveTemplateStatus(boolean status) {
        this.saveTemplateStatus = status;
    }
    public String getSaveTemplateError() {
        return this.saveTemplateError;
    }

    /**
     * Save the contact record template.
     * Called via <apex:actionFunction> tag in VF page.
     */
    public PageReference saveTemplate() {
        // String newContents = Apexpages.currentPage().getParameters().get('templateContents');
        this.reportConfig.Template__c = this.templateContents;
        try {
            update this.reportConfig;
            this.saveTemplateStatus = true;
        } catch (Exception e) {
            this.saveTemplateStatus = false;
            this.saveTemplateError = e.getMessage();
        }
        return null;
    }

/*
    @RemoteAction
    global static List<String> getBargainingUnitsForEmployers(List<String> accountIds) {
        List<String> values = new List<String>();
        AggregateResult[] agRes = [Select BU__c from Contact where AccountId in :accountIds GROUP BY BU__c];
        for (AggregateResult res : agRes)  {
            values.add((String)res.get('BU__c'));
        }
        return values;
    }

    @RemoteAction
    global static List<String> getDepartmentsForEmployers(List<Id> accountIds) {
        System.debug('Searching for contacts related to accounts');
        List<String> values = new List<String>();
        List<AggregateResult> results = [Select Department from Contact where AccountId in :accountIds GROUP BY Department];
        System.debug('Aggregate query returned ' + results.size() + ' records');
        for (AggregateResult res : results) {
            values.add((String)res.get('Department'));
        }
        return values;
    }

    @RemoteAction
    global static List<String> getJobClassesForEmployers(List<String> accountIds) {
        List<String> values = new List<String>();
        for (AggregateResult res : [Select Title from Contact where AccountId in :accountIds GROUP BY Title]) {
            values.add((String)res.get('Title'));
         }
         return values;
    }

*/

}