src/objects/MCL_Report__c.object
<CustomObject>
    <description>MCL</description>
    <fields>
        <fullName>Add_SOQL_Criteria__c</fullName>
        <description>Additional SOQL Criteria.  For Sys Admins only.</description>
        <label>Add SOQL Criteria</label>
        <length>8192</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bargaining_Units__c</fullName>
        <description>Comma-separated list of selected bargaining units.</description>
        <label>Bargaining Units</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Code_List__c</fullName>
        <description>Codes to ignore responses of</description>
        <label>Code List</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Columns__c</fullName>
        <label>Columns</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Coordinator__c</fullName>
        <formula>if (isblank(Employer__r.Coordinator__c), &quot;Vacant&quot;, 
Employer__r.Coordinator__r.FirstName &amp; &quot; &quot; &amp; Employer__r.Coordinator__r.LastName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Coordinator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departments__c</fullName>
        <description>Comma-separated list of selected departments.</description>
        <label>Departments</label>
        <length>8192</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <formula>text(Employer__r.Account_Group__c)</formula>
        <label>Division</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Employer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>MCL_Report_Formats</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Filter_Survey_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Filter Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>MCL Reports</relationshipLabel>
        <relationshipName>MCL_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Filter_Survey_Response__c</fullName>
        <label>Filter Survey Response</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Classes__c</fullName>
        <description>Comma-separated list of selected job classes.</description>
        <label>Job Classes</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Map_Gamma__c</fullName>
        <defaultValue>0.2</defaultValue>
        <label>Map Gamma</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Map_Height__c</fullName>
        <defaultValue>300</defaultValue>
        <label>Map Height</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Map_Width__c</fullName>
        <defaultValue>300</defaultValue>
        <label>Map Width</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Map_Zoom_Level__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Map Zoom Level</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Organizer__c</fullName>
        <formula>if (isblank(Employer__r.Organizer_1__c), &quot;Vacant&quot;, 
Employer__r.Organizer_1__r.FirstName &amp; &quot; &quot; &amp; Employer__r.Organizer_1__r.LastName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organizer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Orientation__c</fullName>
        <label>Orientation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Portrait</fullName>
                </value>
                <value>
                    <fullName>Landscape</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Page_Size__c</fullName>
        <label>Page Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Letter (8.5x11)</fullName>
                </value>
                <value>
                    <fullName>Legal (8.5x14)</fullName>
                </value>
                <value>
                    <fullName>A4</fullName>
                </value>
                <value>
                    <fullName>Envelope #10</fullName>
                </value>
                <value>
                    <fullName>11x17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prefilter_By_Current_BU__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prefilter By Current BU</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Prefilter_Report_Tags__c</fullName>
        <description>Comma separated list of tags.  If any Contact record contains that tag in that record&apos;s Report Tags field, the Contact record will be included.</description>
        <label>Prefilter Report Tags</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Records_with_no_responses__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only return records that don&apos;t have a survey response for the listed codes</description>
        <label>Ignore Contacts with following SR codes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Row_height__c</fullName>
        <defaultValue>4.0</defaultValue>
        <description>The number of headers that consume the same amount of vertical space as one record.</description>
        <inlineHelpText>The number of headers that consume the same amount of vertical space as one record.</inlineHelpText>
        <label>Row height (in headers)</label>
        <precision>9</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rows__c</fullName>
        <inlineHelpText>Maximum number of records to be displayed in one column.</inlineHelpText>
        <label>Rows</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sorting_Config__c</fullName>
        <label>Sorting Config</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <label>Template</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>UHW_Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>UHW Campaign</label>
        <referenceTo>UHW_Campaign__c</referenceTo>
        <relationshipName>MCL_Report_Formats</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>MCL Report</label>
    <nameField>
        <label>MCL Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCL Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Survey Description</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>UHW_Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>UHW Campaign</label>
        <referenceTo>UHW_Campaign__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/UHW_Campaign__c.object
<CustomObject>
    <label>UHW Campaign</label>
    <nameField>
        <label>UHW Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UHW Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MclDuplicationController.cls
public class MclDuplicationController {
    
    @RemoteAction
    public static List <Account> getAccountData() {

        integer recLimit;
        if(Test.isRunningTest())
            recLimit = 1;
        else
            recLimit = 9999999;

        List <Account> accountData;
        if(accountData == null) {
           accountData = [
                Select Id,Account_Group__c,Region__c,Name,Hospital_System__c
                From Account
                Where Account_Group__c In ('New Organizing','Kaiser','Hospital') and Type In ('Prospect','Employer') Order By Account_Group__c,Account.Name LIMIT :recLimit
            ];
        }
        return accountData;
    }

    @RemoteAction
    public static List <sObject> getMclData() {

        integer recLimit;
        if(Test.isRunningTest())
            recLimit = 1;
        else
            recLimit = 9999999;

        List <sObject> mclActData;
        if(mclActData == null) {
            mclActData = [
                SELECT Employer__c,Id,Name,LastModifiedDate,lastModifiedBy.Name,Employer__r.Id,Employer__r.Region__c,Employer__r.Account_Group__c, Employer__r.Name
                FROM MCL_Report__c ORDER BY Name,LastModifiedDate DESC
            ];
        }
        return mclActData;
    }

    @RemoteAction
    public static List <String> createDuplicates(ID id, String baseName, String accountIds,  Boolean srOpt, Boolean filterOpt, Boolean sortOpt) {

        Integer i,j,accountLen,recLimit;
        MCL_Report__c tmpRec;
        MCL_Sort_Entry__c tmpSortRec;
        Account tmpActRec;
        Id mclId;
        Boolean noError = true;
        String name;
        String description;

        List<String> idArray = accountIds.split(',');
        List <Account> accountData;
        List <MCL_Report__c> mclData;
        List <MCL_Report__c> mclRecordsToInsert = new List <MCL_Report__c>();
        List <Id> mclInsertedIds = new List <Id>(); 
        List <MCL_Sort_Entry__c> sortData;
        List <MCL_Sort_Entry__c> sortRecordsToInsert = new List <MCL_Sort_Entry__c>();
        List <Database.SaveResult> srList;
        List <String> errorList = new List <String>();

        if (Test.isRunningTest())
            recLimit = 1;
        else
            recLimit = 9999999;

        if (accountData == null) {
            accountData = [SELECT Id,Name FROM Account WHERE Id In :idArray ORDER BY Name LIMIT: recLimit];
            accountLen  = accountData.size();
        }

        if (mclData == null) {
            mclData = [
                SELECT Add_SOQL_Criteria__c,Bargaining_Units__c,Code_List__c,Columns__c, Coordinator__c, Departments__c,Description__c,Division__c,Employer__c,
                       Filter_Survey_Question__c,Filter_Survey_Response__c,Job_Classes__c,Map_Gamma__c,Map_Height__c,Map_Width__c,Map_Zoom_Level__c,
                       Organizer__c,Orientation__c,Page_Size__c,Prefilter_By_Current_BU__c,Prefilter_Report_Tags__c,Rows__c,Row_height__c,Sorting_Config__c,Template__c,UHW_Campaign__c,Records_with_no_responses__c
                FROM MCL_Report__c
                WHERE Id = :id
                ORDER BY LastModifiedDate DESC NULLS FIRST
                LIMIT: recLimit
                
            ];

            sortData = [
                SELECT Contact_Field_Name__c,Header__c,MCL_Report__c,Page_Break__c,Sort_Level__c,Sort_Order__c,Survey_Question__c FROM MCL_Sort_Entry__c WHERE MCL_Report__c = :id AND IsDeleted = false
            ];
            if(mclData.size() > 0 ) {
                system.debug(sortData);
            }
            else {
                system.debug('No sort data for this MCL');
            }

            if(mclData.size() > 0 ) {
                if(accountLen > 0) {
                    description = mclData[0].Description__c;
                    if(String.isEmpty(description))
                       description  = '[Created with MclDuplicator]';
                    else
                       description += '\n[Created with MclDuplicator]';

                    for(i=0;i<accountLen;i++) {
                        tmpActRec = accountData[i];
                        tmpRec = new MCL_Report__c();
                        tmpRec.Add_SOQL_Criteria__c       = mclData[0].Add_SOQL_Criteria__c;
                        tmpRec.Columns__c                 = mclData[0].Columns__c;
                        tmpRec.Description__c             = description;
                        tmpRec.Employer__c                = tmpActRec.Id;
                        tmpRec.Filter_Survey_Question__c  = mclData[0].Filter_Survey_Question__c;
                        tmpRec.Filter_Survey_Response__c  = mclData[0].Filter_Survey_Response__c;
                        tmpRec.Map_Gamma__c               = mclData[0].Map_Gamma__c;
                        tmpRec.Map_Height__c              = mclData[0].Map_Height__c;
                        tmpRec.Map_Width__c               = mclData[0].Map_Width__c;
                        tmpRec.Map_Zoom_Level__c          = mclData[0].Map_Zoom_Level__c;
                        tmpRec.Name                       = baseName + ' (' + tmpActRec.Name + ')';
                        tmpRec.Orientation__c             = mclData[0].Orientation__c;
                        tmpRec.Page_Size__c               = mclData[0].Page_Size__c;
                        tmpRec.Prefilter_By_Current_BU__c = mclData[0].Prefilter_By_Current_BU__c;
                        tmpRec.Prefilter_Report_Tags__c   = mclData[0].Prefilter_Report_Tags__c;
                        tmpRec.Rows__c                    = mclData[0].Rows__c;
                        tmpRec.Row_height__c              = mclData[0].Row_height__c;
                        tmpRec.Sorting_Config__c          = mclData[0].Sorting_Config__c;
                        tmpRec.Template__c                = mclData[0].Template__c;
                        tmpRec.UHW_Campaign__c            = mclData[0].UHW_Campaign__c;
                        if(srOpt) {
                            tmpRec.Records_with_no_responses__c = mclData[0].Records_with_no_responses__c;
                            tmpRec.Code_List__c                 = mclData[0].Code_List__c;
                        }
                        if(filterOpt) {
                            tmpRec.Job_Classes__c         = mclData[0].Job_Classes__c;
                            tmpRec.Departments__c         = mclData[0].Departments__c;
                            tmpRec.Bargaining_Units__c    = mclData[0].Bargaining_Units__c;
                        }
                        mclRecordsToInsert.add(tmpRec);
                    }
                    // ------------------------------------------------------------------------------------------- //
                    // Insert Mcl Records 
                    // ------------------------------------------------------------------------------------------- //
                    if (!mclRecordsToInsert.isEmpty()) {
                        try {
                            srList = Database.insert(mclRecordsToInsert, false);
                            for (Database.SaveResult sr : srList) {
                                if (!sr.isSuccess()) {
                                    errorList.add('Error 1:' + sr.Errors[0].StatusCode);
                                    noError = false;
                                }
                                else {
                                    mclId = sr.getId();
                                    mclInsertedIds.add(mclId);
                                }
                            }
                        }
                        catch (DmlException e) {
                            errorList.add('Error 2');
                            noError = false;
                        }

                        if(sortOpt && sortData.size() > 0) {
                            if(mclInsertedIds.size() > 0 ) {
                                for(i=0;i<mclInsertedIds.size();i++) {
                                    mclId = mclInsertedIds[i];
                                    for(j=0;j<sortData.size();j++) {
                                        tmpSortRec = new MCL_Sort_Entry__c();
                                        tmpSortRec.MCL_Report__c         = mclId;
                                        tmpSortRec.Contact_Field_Name__c = sortData[j].Contact_Field_Name__c;
                                        tmpSortRec.Header__c             = sortData[j].Header__c;
                                        tmpSortRec.Page_Break__c         = sortData[j].Page_Break__c;
                                        tmpSortRec.Sort_Level__c         = sortData[j].Sort_Level__c;
                                        tmpSortRec.Sort_Order__c         = sortData[j].Sort_Order__c;
                                        tmpSortRec.Survey_Question__c    = sortData[j].Survey_Question__c;
                                        sortRecordsToInsert.add(tmpSortRec);
                                    }
                                }
                                try {
                                    srList = Database.insert(sortRecordsToInsert, false);
                                    for (Database.SaveResult sr : srList) {
                                        if (!sr.isSuccess()) {
                                            errorList.add('Error 3:' + sr.Errors[0].StatusCode);
                                            noError = false;
                                    }
                                }
                            }
                            catch (DmlException e) {
                                errorList.add('Error 4');
                                noError = false;
                                }
                            }
                        }
                    }
                }
            }
        }
        return errorList;
    }
}