src/objects/Recruit__c.object
<CustomObject>
    <description>Political Campaigns/Shifts;</description>
    <fields>
        <fullName>Alt_First_Name__c</fullName>
        <label>Alt First Name</label>
        <length>65</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alt_Last_Name__c</fullName>
        <label>Alt Last Name</label>
        <length>65</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alt_Phone__c</fullName>
        <label>Alt Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attended Old</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credit__c</fullName>
        <label>Credit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Half</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Partial</fullName>
                    <isActive>false</isActive>
                    <label>Partial</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Antelope Valley/Lancaster</fullName>
                    <isActive>false</isActive>
                    <label>Antelope Valley/Lancaster</label>
                </value>
                <value>
                    <fullName>Antelope Valley(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Antelope Valley(2-5)</label>
                </value>
                <value>
                    <fullName>Antelope Valley(5-8)</fullName>
                    <isActive>false</isActive>
                    <label>Antelope Valley(5-8)</label>
                </value>
                <value>
                    <fullName>Arroyo Grande</fullName>
                    <isActive>false</isActive>
                    <label>Arroyo Grande</label>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 10AM-2PM</fullName>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 2PM-6PM</fullName>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 5PM-9PM</fullName>
                </value>
                <value>
                    <fullName>Bakersfield</fullName>
                    <isActive>false</isActive>
                    <label>Bakersfield</label>
                </value>
                <value>
                    <fullName>Bakersfield(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Bakersfield(2-5)</label>
                </value>
                <value>
                    <fullName>Bakersfield(5-8)</fullName>
                    <isActive>false</isActive>
                    <label>Bakersfield(5-8)</label>
                </value>
                <value>
                    <fullName>Bakersfield GOTV 10AM-2PM</fullName>
                </value>
                <value>
                    <fullName>Bakersfield GOTV 11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>Bakersfield GOTV 3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>Bakersfield GOTV 5PM-9PM</fullName>
                </value>
                <value>
                    <fullName>Baldwin</fullName>
                    <isActive>false</isActive>
                    <label>Baldwin</label>
                </value>
                <value>
                    <fullName>Chico</fullName>
                    <isActive>false</isActive>
                    <label>Chico</label>
                </value>
                <value>
                    <fullName>Chico GOTV 11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>Chico GOTV 2PM-6PM</fullName>
                </value>
                <value>
                    <fullName>Chico GOTV 3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>Chico GOTV 5PM-9PM</fullName>
                </value>
                <value>
                    <fullName>Fresno</fullName>
                    <isActive>false</isActive>
                    <label>Fresno</label>
                </value>
                <value>
                    <fullName>Fresno Early(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Fresno Early(2-5)</label>
                </value>
                <value>
                    <fullName>Fresno GOTV 10AM-2PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 12PM-4PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 2PM-6PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 4PM-8PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recruit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If the recruit is not a member or a community, leave this blank. Enter the recruit on the Family/Friends section.</inlineHelpText>
        <label>Recruit</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recruits</relationshipLabel>
        <relationshipName>Recruits3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recruited_By__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the person getting the credit (member or organizer/rep).</inlineHelpText>
        <label>Recruited By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recruits (Recruited By)</relationshipLabel>
        <relationshipName>Recruits4</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shift__c</fullName>
        <label>Shift</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Location__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Morning</fullName>
                </value>
                <value>
                    <fullName>Afternoon</fullName>
                </value>
                <value>
                    <fullName>Evening</fullName>
                </value>
                <value>
                    <fullName>10AM-2PM</fullName>
                </value>
                <value>
                    <fullName>11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>2PM-6PM</fullName>
                </value>
                <value>
                    <fullName>3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>5PM-9PM</fullName>
                </value>
                <value>
                    <fullName>12PM-4PM</fullName>
                </value>
                <value>
                    <fullName>12N-4PM</fullName>
                </value>
                <value>
                    <fullName>4PM-8PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Volunteer Date</label>
        <type>Date</type>
    </fields>
    <label>Recruit</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Recruit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recruits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SignInRemoteController1.cls
public class SignInRemoteController1 {

    @RemoteAction
    public static List <sObject> getData(String cutoffDateStr) {

        date cutoffDate  = date.valueOf(cutoffDateStr);
        integer recLimit;

        if(Test.isRunningTest())
          recLimit = 2;
        else
          recLimit = 9999999;

        list <sObject> data;
        if(data == null) {
          data = new List <sObject>();
          integer i,l;
          sObject tmpRec;

          for (list <sObject> dataList : [
            SELECT Recruit__r.Email, Recruit__r.FirstName, Recruit__r.HomePhone, Recruit__r.Id, Recruit__r.LastName, Recruit__r.MobilePhone, Recruit__r.OK_To_Text__c,  Recruit__r.Ethnic_Group__c,
            Recruit__r.Cope_Amount__c, Recruit__r.Cope_Payment_Date__c, Recruit__r.Employer1__c, Recruited_By__r.FirstName, Recruited_By__r.LastName,
            Alt_First_Name__c, Alt_Last_Name__c, Alt_Phone__c, Attended__c, Credit__c, Volunteer_Date__c, Id, Location__c, Shift__c
            From Recruit__c
            Where  Volunteer_Date__c >= :cutoffDate And Shift__c != null
            Order By Volunteer_Date__c,location__c,Shift__c Limit :recLimit
          ]) {
            l = dataList.size();
            for(i=0;i<l;i++) {
              tmpRec = dataList[i];
              data.add(tmpRec);
            }
          }
      }
      return data;
    }

    @RemoteAction
    public static List<String> RecruitUpdate(List <String> updates) {

        List <String> errorList;
        List <Database.DeleteResult> drList;
        List <Database.SaveResult>   srList;
        List <Recruit__c> recruitsToUpdate;
        List <Contact> contactsToUpdate;

        RecruitTx  tmpRecruitTx;
        Recruit__c tmpRecruit;
        Contact    tmpContact;

        recruitsToUpdate = new List <Recruit__c>();
        contactsToUpdate = new List <Contact>();
        errorList        = new List <String>();
        Boolean noError  = true;

        for (String RecruitRec : updates) {
            tmpRecruit   = new Recruit__c();
            tmpRecruitTx = RecruitTx.parse(RecruitRec);

            tmpRecruit.Id           = tmpRecruitTx.RecruitRecId;
            if(tmpRecruitTx.Credit != 'empty')
              tmpRecruit.Credit__c  = tmpRecruitTx.Credit;

            tmpRecruit.Attended__c  = tmpRecruitTx.Attended;
            recruitsToUpdate.add(tmpRecruit);

            // Recruit may not be a contact.
            if(!String.IsEmpty(tmpRecruitTx.ContactId)) {

              if(tmpRecruitTx.OkToText || tmpRecruitTx.EthnicGroup != 'empty') {
                tmpContact               = new Contact();
                tmpContact.Id            = tmpRecruitTx.ContactId;
                tmpContact.OK_To_Text__c = tmpRecruitTx.OkToText;

                if(tmpRecruitTx.EthnicGroup != 'empty')
                  tmpContact.Ethnic_Group__c = tmpRecruitTx.EthnicGroup;

                  contactsToUpdate.add(tmpContact);
              }
            }
        }

        // ------------------------------------------------------------------------------------------- //
        // Update Recruits
        // ------------------------------------------------------------------------------------------- //
        if (!recruitsToUpdate.isEmpty()) {
          try {
            srList = Database.update(recruitsToUpdate, false);
            for (Database.SaveResult sr : srList) {
              if (!sr.isSuccess()) {
                errorList.add('Error 1:' + sr.Errors[0].StatusCode);
                noError = false;
              }
            }
          }
          catch (DmlException e) { errorList.add('Error 2'); noError = false; }
        }

        // ------------------------------------------------------------------------------------------- //
        // Update Contacts
        // ------------------------------------------------------------------------------------------- //
        if (!contactsToUpdate.isEmpty()) {
          try {
            srList = Database.update(contactsToUpdate, false);
            for (Database.SaveResult sr : srList) {
              if (!sr.isSuccess()) {
                errorList.add('Error 3:' + sr.Errors[0].StatusCode);
                noError = false;
              }
            }
          }
          catch (DmlException e) { errorList.add('Error 4'); noError = false; }
        }

        return errorList;
    }
}