src/objects/Recruit__c.object
<CustomObject>
    <description>Political Campaigns/Shifts;</description>
    <fields>
        <fullName>FID__c</fullName>
        <formula>Recruit__r.FID__c</formula>
        <label>FID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Antelope Valley/Lancaster</fullName>
                    <isActive>false</isActive>
                    <label>Antelope Valley/Lancaster</label>
                </value>
                <value>
                    <fullName>Antelope Valley(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Antelope Valley(2-5)</label>
                </value>
                <value>
                    <fullName>Antelope Valley(5-8)</fullName>
                    <isActive>false</isActive>
                    <label>Antelope Valley(5-8)</label>
                </value>
                <value>
                    <fullName>Arroyo Grande</fullName>
                    <isActive>false</isActive>
                    <label>Arroyo Grande</label>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 10AM-2PM</fullName>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 2PM-6PM</fullName>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 5PM-9PM</fullName>
                </value>
                <value>
                    <fullName>Bakersfield</fullName>
                    <isActive>false</isActive>
                    <label>Bakersfield</label>
                </value>
                <value>
                    <fullName>Bakersfield(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Bakersfield(2-5)</label>
                </value>
                <value>
                    <fullName>Bakersfield(5-8)</fullName>
                    <isActive>false</isActive>
                    <label>Bakersfield(5-8)</label>
                </value>
                <value>
                    <fullName>Bakersfield GOTV 10AM-2PM</fullName>
                </value>
                <value>
                    <fullName>Bakersfield GOTV 11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>Bakersfield GOTV 3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>Bakersfield GOTV 5PM-9PM</fullName>
                </value>
                <value>
                    <fullName>Baldwin</fullName>
                    <isActive>false</isActive>
                    <label>Baldwin</label>
                </value>
                <value>
                    <fullName>Chico</fullName>
                    <isActive>false</isActive>
                    <label>Chico</label>
                </value>
                <value>
                    <fullName>Chico GOTV 11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>Chico GOTV 2PM-6PM</fullName>
                </value>
                <value>
                    <fullName>Chico GOTV 3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>Chico GOTV 5PM-9PM</fullName>
                </value>
                <value>
                    <fullName>Fresno</fullName>
                    <isActive>false</isActive>
                    <label>Fresno</label>
                </value>
                <value>
                    <fullName>Fresno Early(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Fresno Early(2-5)</label>
                </value>
                <value>
                    <fullName>Fresno GOTV 10AM-2PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 12PM-4PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 2PM-6PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 4PM-8PM</fullName>
                </value>
                <value>
                    <fullName>Oakland Early(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Oakland Early(2-5)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recruit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If the recruit is not a member or a community, leave this blank. Enter the recruit on the Family/Friends section.</inlineHelpText>
        <label>Recruit</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recruits</relationshipLabel>
        <relationshipName>Recruits3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recruited_By__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the person getting the credit (member or organizer/rep).</inlineHelpText>
        <label>Recruited By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recruits (Recruited By)</relationshipLabel>
        <relationshipName>Recruits4</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Volunteer Date</label>
        <type>Date</type>
    </fields>
    <label>Recruit</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Recruit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recruits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Recruit_To_SurveyTest.cls
@isTest(SeeAllData = true)
public class Recruit_To_SurveyTest {

  public static testMethod  void testPropagate() {

  
    Account em = new Account(name='Test Employer');
    insert em;
  
    Contact c = new Contact();
    c.lastname = ('TestLast');
    c.firstName = ('TestFirst');
    c.fid__c = '9999-169990001';
    c.account = em;    
    insert c;
    
    Recruit__c r = new Recruit__c();
    
    r.Recruit__c = c.Id;
    r.Volunteer_Date__c = Date.today();
    r.Location__c = 'Oakland Early(2-5)';
    r.Recruited_By__c = c.Id;
    
    insert r;
    
    Recruit_To_Survey.cheese();
  }
  
}