src/objects/Recruit__c.object
<CustomObject>
    <description>Political Campaigns/Shifts;</description>
    <fields>
        <fullName>Alt_Employer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Alt Employer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recruits</relationshipLabel>
        <relationshipName>Recruits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Alt_First_Name__c</fullName>
        <label>Alt First Name</label>
        <length>65</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alt_Last_Name__c</fullName>
        <label>Alt Last Name</label>
        <length>65</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alt_Middle_Name__c</fullName>
        <label>Alt Middle Name</label>
        <length>65</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alt_Person_Type__c</fullName>
        <label>Alt Person Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alllies</fullName>
                    <label>Allies</label>
                </value>
                <value>
                    <fullName>Friends/Family</fullName>
                </value>
                <value>
                    <fullName>Not Yet Union</fullName>
                </value>
                <value>
                    <fullName>Pre-member Community</fullName>
                </value>
                <value>
                    <fullName>Pre-member Hospital/Kaiser</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employer_Name__c</fullName>
        <formula>IF( AND(AND(AND(Recruit__r.Account.Name =&quot;SEIU-UHW&quot;), Alt_Last_Name__c &lt;&gt;&quot;&quot;), TEXT(Alt_Person_Type__c)=&quot;Friend/Family of UHW Staff&quot; ),&quot;STAFF GUEST&quot;
,
IF(ISBLANK( Alt_Employer__c), IF (ISBLANK(Recruit__r.Employer1__c), Recruited_By__r.Account.Name,Recruit__r.Employer1__c),  Alt_Employer__r.Name ))</formula>
        <label>Employer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Antelope Valley/Lancaster</fullName>
                    <isActive>false</isActive>
                    <label>Antelope Valley/Lancaster</label>
                </value>
                <value>
                    <fullName>Antelope Valley(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Antelope Valley(2-5)</label>
                </value>
                <value>
                    <fullName>Antelope Valley(5-8)</fullName>
                    <isActive>false</isActive>
                    <label>Antelope Valley(5-8)</label>
                </value>
                <value>
                    <fullName>Arroyo Grande</fullName>
                    <isActive>false</isActive>
                    <label>Arroyo Grande</label>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 10AM-2PM</fullName>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 2PM-6PM</fullName>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>Arroyo Grande GOTV 5PM-9PM</fullName>
                </value>
                <value>
                    <fullName>Bakersfield</fullName>
                    <isActive>false</isActive>
                    <label>Bakersfield</label>
                </value>
                <value>
                    <fullName>Bakersfield(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Bakersfield(2-5)</label>
                </value>
                <value>
                    <fullName>Bakersfield(5-8)</fullName>
                    <isActive>false</isActive>
                    <label>Bakersfield(5-8)</label>
                </value>
                <value>
                    <fullName>Bakersfield GOTV 10AM-2PM</fullName>
                </value>
                <value>
                    <fullName>Bakersfield GOTV 11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>Bakersfield GOTV 3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>Bakersfield GOTV 5PM-9PM</fullName>
                </value>
                <value>
                    <fullName>Baldwin</fullName>
                    <isActive>false</isActive>
                    <label>Baldwin</label>
                </value>
                <value>
                    <fullName>Chico</fullName>
                    <isActive>false</isActive>
                    <label>Chico</label>
                </value>
                <value>
                    <fullName>Chico GOTV 11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>Chico GOTV 2PM-6PM</fullName>
                </value>
                <value>
                    <fullName>Chico GOTV 3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>Chico GOTV 5PM-9PM</fullName>
                </value>
                <value>
                    <fullName>Fresno</fullName>
                    <isActive>false</isActive>
                    <label>Fresno</label>
                </value>
                <value>
                    <fullName>Fresno Early(2-5)</fullName>
                    <isActive>false</isActive>
                    <label>Fresno Early(2-5)</label>
                </value>
                <value>
                    <fullName>Fresno GOTV 10AM-2PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 11AM-3PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 12PM-4PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 2PM-6PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 3:30PM-7:30PM</fullName>
                </value>
                <value>
                    <fullName>Fresno GOTV 4PM-8PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recruit_Name__c</fullName>
        <formula>IF( AND(AND(AND(Recruit__r.Account.Name =&quot;SEIU-UHW&quot;), Alt_Last_Name__c &lt;&gt;&quot;&quot;), TEXT(Alt_Person_Type__c)=&quot;Friend/Family of UHW Staff&quot; ), Alt_Last_Name__c &amp; &quot;, &quot; &amp;  Alt_First_Name__c, if (or(isnull( Recruit__c ),isblank(Recruit__c)),
if(or(isnull(Alt_Middle_Name__c), isblank(Alt_Middle_Name__c)),
         Alt_Last_Name__c &amp; &quot;, &quot; &amp;  Alt_First_Name__c,
         Alt_Last_Name__c &amp; &quot;, &quot; &amp;  Alt_First_Name__c &amp; &quot; &quot; &amp;  Alt_Middle_Name__c
      )
    ,
      if(or(isnull(Recruit__r.MiddleName), isblank(Recruit__r.MiddleName)),
         Recruit__r.LastName &amp; &quot;, &quot; &amp;  Recruit__r.FirstName, 
         Recruit__r.LastName &amp; &quot;, &quot; &amp; Recruit__r.FirstName &amp; &quot; &quot; &amp; Recruit__r.MiddleName
      )
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Recruit Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recruit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If the recruit is not a member or a community, leave this blank. Enter the recruit on the Family/Friends section.</inlineHelpText>
        <label>Recruit</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recruits</relationshipLabel>
        <relationshipName>Recruits3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recruited_By__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This is the person getting the credit (member or organizer/rep).</inlineHelpText>
        <label>Recruited By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recruits (Recruited By)</relationshipLabel>
        <relationshipName>Recruits4</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Shift__c</fullName>
        <formula>IF( Attended__c =TRUE, CASE(  CreditShift__c , &apos;Full&apos;, 1, &apos;Half&apos;, 0.5,0), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Shift Completed</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Volunteer_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Volunteer Date</label>
        <type>Date</type>
    </fields>
    <label>Recruit</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Recruit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recruits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>What date did this survey question come online?</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Linked_to_Recruits__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Does this SQ link to the Recruits custom object?</description>
        <label>Linked to Recruits</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <description>Three letter Survey Code</description>
        <externalId>true</externalId>
        <label>Survey Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Add_Info__c</fullName>
        <label>Additional Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Alt_Employer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Alt Employer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Alt_First_Name__c</fullName>
        <label>Alt First Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alt_Last_Name__c</fullName>
        <label>Alt Last Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alt_Middle_Name__c</fullName>
        <label>Alt Middle Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alt_Person_Type__c</fullName>
        <description>If the Survey Response is entered for someone not in Salesforce, the Organizer should indicate whether this person is a Member or someone else who is a non-member.</description>
        <label>Alt Person Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Allies</fullName>
                </value>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Friend/Family of Member</fullName>
                </value>
                <value>
                    <fullName>Medi-Cal Beneficiary</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Non-Member in Facility</fullName>
                </value>
                <value>
                    <fullName>NYU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact Survey Response</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employer_Name__c</fullName>
        <formula>if (or(isnull(Contact__c), isblank(Contact__c)),  Alt_Employer__r.Name,  Contact__r.Account.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Value__c</fullName>
        <label>Response Value</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <formula>Survey_Question__r.Survey_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Survey Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Survey Question</description>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Survey Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Recruit_To_Survey.cls
/*
 * Recruit to Survey - helper for Recruit Trigger Controller
 * 
 * Version: 1.02
 * 17th Oct 2016
 * 
 * Version History
 * 1.03 - made @future annotation.
 * 1.02 - more bug fixes
 * 1.01 - bug fixes
 * 1.0 - created, 20th Sep 2016
 * 
 * Copyright (c) 2016 SEIU-UHW
 * 560 Thomas L Berkley Way
 * Oakland, CA 94612, USA
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of SEIU-UHW.
 * ('Confidential Information').
 */
public class Recruit_To_Survey { 

    public Recruit_To_Survey() {
      //ignore
    }

    @future
    public static void propagateToSurvey(Set<Id> pNewIdSet, Set<Id> pOldIdSet, Boolean pIsInsert, Boolean pIsDelete) {
      Recruit__c debugRecruit = null;

      List<Recruit__c> pNewList = null;
      if (pNewIdSet!= null && pNewIdSet.size() > 0) {      
        pNewList = [select Id, Volunteer_Date__c, Recruited_By__c, Recruit_Name__c, Recruit__c, Alt_Last_Name__c, Alt_First_Name__c, Alt_Middle_Name__c, Alt_Person_Type__c, Alt_Employer__c, Employer_Name__c, Location__c, Total_Shift__c from Recruit__c where Id in :pNewIdSet];
      }
      List<Recruit__c> pOldList = null;
      if (pOldIdSet != null && pOldIdSet.size() > 0) {
        pOldList = [select Id, Volunteer_Date__c, Recruited_By__c, Recruit_Name__c, Recruit__c, Alt_Last_Name__c, Alt_First_Name__c, Alt_Middle_Name__c, Alt_Person_Type__c, Alt_Employer__c, Employer_Name__c, Location__c, Total_Shift__c from Recruit__c where Id in :pOldIdSet];
      }
      try {

        Set<String> emNameSet = new Set<String>();
        

        List<Data_Group__c> dataParams = [ select Value__c from Data_Group__c where Name = 'Default_Employer_Name' limit 1 ];
        Account defaultEmployer = null;      
        if (dataParams != null) {
          String defaultEmployerName = dataParams[0].Value__c;
          List<Account> defaultEmployerList = [select Id, Name from Account where Name = :defaultEmployerName];
          if (defaultEmployerList != null && defaultEmployerList.size() > 0) {
            defaultEmployer = defaultEmployerList[0];
          }
        }      
      
        List<Survey_Question__c> sqList = [select Id, Effective_Date__c, End_Date__c, Name, Survey_Code__c from Survey_Question__c where Linked_to_Recruits__c  = true and Effective_Date__c <= TODAY and End_Date__c >= TODAY ];
     
        if (sqList.size() == 0) {
          return; 
        } else if (sqList.size() > 1) {
          String errString = 'There are multiple active Survey Questions linked to Recruits in the system.  Only one Survey Question can be linked to Recruits at a time.';
          for (Recruit__c r: pNewList) {
            r.addError(errString);
          }
          return;
        }   
        
        Map<String, Recruit__c> oldAltMap = new Map<String, Recruit__c>();
        Map<Id, Recruit__c> oldCidMap = new Map<Id, Recruit__c>();
        
        if (!pIsInsert && pNewList != null) {
          Integer noChangeCount = 0;
          Map<Id, Recruit__c> oldMap = new Map<Id, Recruit__c>();
          for (Recruit__c r: pOldList) {
            emNameSet.add(r.Employer_Name__c);
            oldMap.put(r.Id, r);
            String altKey = null;
            if (r.Recruit__c == null) {
              altKey = (r.Alt_First_Name__c + ';' + r.Alt_Last_Name__c  + ';' +  r.Employer_Name__c).toLowerCase();        
              oldAltMap.put(altKey, r);
            } else {
              oldCidMap.put(r.Recruit__c, r);
            }                          
          }
          for (Recruit__c r: pNewList) {
            debugRecruit = r;        
            emNameSet.add(r.Employer_Name__c);            
            if (oldMap.containsKey(r.Id)) {
              if (oldMap.get(r.Id).Total_Shift__c == r.Total_Shift__c) {
                noChangeCount++;
              }
            }
          }
          if (noChangeCount == pNewList.size()) {
            System.debug('No changes to Total Shifts, Recruit to Survey Response not updating SRs.');
            return;
          }
        }
        
        Map<String, Account> emNameMap = new Map<String, Account>();
        List<Account> emList = [ select Id, Name from Account where Name in :emNameSet];
        for (Account em: emList ) {        
          emNameMap.put(em.Name, em);
        }
      
        List<Id> newIdList = new List<Id>();
           
        //List<Id> sqidList = new List<Id>();
        Date startDate;
        Date endDate;  
        Id sqid;    
        for (Survey_Question__c sq: sqList) {
          sqid = sq.Id;
          startDate = sq.Effective_Date__c;
          endDate = sq.End_Date__c;
        }
        Set<Id> ridSet = new Set<Id>();  
      
        Map<Id, Id> collectorMap = new Map<Id, Id>();
        Map<Id, Double> countMap = new Map<Id, Double>();
        Map<Id, Date> dateMap = new Map<Id, Date>();      

        Map<String, Id> altCollectorMap = new Map<String, Id>();      
        Map<String, Recruit__c> altPersonMap = new Map<String, Recruit__c>();    
        Map<String, Double> altCountMap = new Map<String, Double>();            
        Set<String> altKeySet = new Set<String>();         
        Set<Id> altEmSet = new Set<Id>();         
        Map<String, Date> altDateMap = new Map<String, Date>();      
      
        String debugAltEmId = '';
      
      
        System.debug('cycling through new Recruits...');
      
        if (pNewList != null) {    
          for (Recruit__c r: pNewList) {
            debugRecruit = r;
            String altKey = null;
            if (r.Recruit__c == null) {
              altKey = (r.Alt_First_Name__c + ';' + r.Alt_Last_Name__c  + ';' +  r.Employer_Name__c).toLowerCase();        
              if (!altCountMap.containsKey(altKey)) {
                 altCountMap.put(altKey , 0.0);
              }   
              System.debug('adding alt key = ' + altKey);
              altKeySet.add(altKey);          
            } else {
              if (!countMap.containsKey(r.Recruit__c)) {
                countMap.put(r.Recruit__c, 0.0);
              }
            }
            
            
            
            if (r.Volunteer_Date__c >= startDate && r.Volunteer_Date__c <= endDate) {
              newIdList.add(r.Id);
              if (r.Recruit__c != null) {
                ridSet.add(r.Recruit__c);

                if (r.Recruited_By__c != null && !collectorMap.containsKey(r.Recruit__c)) {
                  collectorMap.put(r.Recruit__c, r.Recruited_By__c);
                }    
                Double shiftCount = 0;
                if ( countMap.containsKey( r.Recruit__c)) {
                  shiftCount = countMap.get( r.Recruit__c);
                }
                //String debugString = '';
                //if (debugMap.containsKey(r.Recruit__c)) {
                //  debugString = debugMap.get(r.Recruit__c);
                //}
                //debugString += r.Volunteer_Date__c + ' (' + r.Total_Shift__c + '); ';
                //debugMap.remove(r.Recruit__c);
                //debugMap.put(r.Recruit__c, debugString);
                shiftCount = shiftCount + r.Total_Shift__c;
                countMap.remove(r.Recruit__c);        
                countMap.put( r.Recruit__c, shiftCount);
                dateMap.put( r.Recruit__c, r.Volunteer_Date__c); 
              } else {
                //ALT PERSON ROLLUP
                
                altPersonMap.put(altKey, r);
                Double shiftCount = 0;
                if ( altCountMap.containsKey( altKey)) {
                  shiftCount = altCountMap.get(altKey);
                }
                shiftCount = shiftCount + r.Total_Shift__c;
                altCountMap.remove(altKey);        
                altCountMap.put(altKey, shiftCount);
                altDateMap.put(altKey, r.Volunteer_Date__c);               
                altEmSet.add(r.Alt_Employer__c);
                debugAltEmId = r.Alt_Employer__c;
                if (r.Recruited_By__c != null && !altCollectorMap.containsKey(altKey)) {
                  altCollectorMap.put(altKey, r.Recruited_By__c);
                }      
                               
              }
            }
          }
        }
        if (pOldList != null) {
          for (Recruit__c r: pOldList) {
            debugRecruit = r;
            String altKey = null;
            if (r.Recruit__c == null) {
              altKey = (r.Alt_First_Name__c + ';' + r.Alt_Last_Name__c  + ';' +  r.Employer_Name__c).toLowerCase();        
              if (!altCountMap.containsKey(altKey)) {
                 altCountMap.put(altKey , 0.0);
              }           
              System.debug('adding alt key = ' + altKey);              
              altKeySet.add(altKey); 
              altEmSet.add(r.Alt_Employer__c);  
              debugAltEmId = r.Alt_Employer__c;             
            } else {
              if (!countMap.containsKey(r.Recruit__c)) {
                countMap.put(r.Recruit__c, 0.0);
              }
              ridSet.add(r.Recruit__c);              
            }        
          }       
        } 
        List<Survey_Response__c> srList = [ select Id, Name, Contact__c, Alt_First_Name__c, Alt_Middle_Name__c, Alt_Last_Name__c, Alt_Person_Type__c, Alt_Employer__c, Employer_Name__c, Add_Info__c from Survey_Response__c where Survey_Question__c = :sqid and (Contact__c in :ridSet OR Alt_Employer__c = :debugAltEmId )  ];      
        Map<Id, Survey_Response__c> srMap = new Map<Id, Survey_Response__c>();
        Map<String, Survey_Response__c> altSrMap = new Map<String, Survey_Response__c>();  
        
        String debugSrKey = '';
          
        for (Survey_Response__c sr: srList) {
          if (sr.Contact__c != null) {
            srMap.put(sr.Contact__c, sr);
          } else {
            String altKey = (sr.Alt_First_Name__c + ';' + sr.Alt_Last_Name__c  + ';' +  sr.Employer_Name__c).toLowerCase();                  
            altSrMap.put(altKey , sr);
            debugSrKey = altKey;
          }
        }
        List<Recruit__c> rList = [ select Id, Name, Recruit__c, Volunteer_Date__c, Recruited_By__c, Total_Shift__c, Alt_First_Name__c, Alt_Middle_Name__c, Alt_Last_Name__c, Alt_Employer__c, Alt_Person_Type__c, Employer_Name__c from Recruit__c where (Recruit__c in :ridSet or Alt_Employer__c in :altEmSet) and Volunteer_Date__c <= :endDate and Volunteer_Date__c >= :startDate AND (NOT Id in :newIdList ) ];       
        for (Recruit__c r: rList) {
          debugRecruit = r;
          String altKey = null;
          if (r.Recruit__c == null) {
            altKey = (r.Alt_First_Name__c + ';' + r.Alt_Last_Name__c  + ';' +  r.Employer_Name__c).toLowerCase();                  
            System.debug('altKey = ' + altKey);
            if (!altPersonMap.containsKey(altKey)) {
              altPersonMap.put(altKey, r);               
            }          
          }

        
          if (r.Recruit__c != null && r.Recruited_By__c != null && !collectorMap.containsKey(r.Recruit__c)) {
            collectorMap.put(r.Recruit__c, r.Recruited_By__c);
          } else if (r.Recruit__c == null && r.Recruited_By__c != null  ) {
            if ( !altCollectorMap.containsKey(altKey)) {
              altCollectorMap.put(altKey, r.Recruited_By__c);
            }
          }
          Double shiftCount = 0;
          if (r.Recruit__c != null && countMap.containsKey( r.Recruit__c)) {
            shiftCount = countMap.get( r.Recruit__c);
          } else if (r.Recruit__c == null && altCountMap.containsKey(altKey)) {
  
            shiftCount = altCountMap.get(altKey);
          }

          //String debugString = '';
          //if (debugMap.containsKey(r.Recruit__c)) {
          //  debugString = debugMap.get(r.Recruit__c);
          //}
          //debugString += r.Volunteer_Date__c + ' (' + r.Total_Shift__c + '); ';
          //debugMap.remove(r.Recruit__c);
          //debugMap.put(r.Recruit__c, debugString);
        
          shiftCount = shiftCount + r.Total_Shift__c;
          if (r.Recruit__c != null) {        
            if (countMap.containsKey( r.Recruit__c)) {
              countMap.remove(r.Recruit__c);
            }
            System.debug('adding count to countMap = ' + shiftCount);
            countMap.put( r.Recruit__c, shiftCount);                
          } else if (r.Recruit__c == null) {
            if (altCountMap.containsKey( altKey )) {
              altCountMap.remove( altKey );
            }
            altCountMap.put( altKey, shiftCount);                
          }

          if (r.Recruit__c != null && !dateMap.containsKey(r.Recruit__c)) {
            dateMap.put( r.Recruit__c, r.Volunteer_Date__c); 
          } else if (r.Recruit__c == null && !altDateMap.containsKey(altKey)) {
            altDateMap.put( altKey , r.Volunteer_Date__c); 
          }                 
        }

        System.debug('construct SRs for Recruits with a Contact records.');
        List<Survey_Response__c> insertSrList = new List<Survey_Response__c>();
        for (Id rid: ridSet) { 
          Survey_Response__c sr = new Survey_Response__c();
          Double oldCount = -1.0;
          if (srMap.containsKey(rid)) {
            sr = srMap.get(rid);
          } else {
            sr.Survey_Question__c = sqid;
            sr.Response_Value__c = 'yes';
            sr.Contact__c = rid;        
          }
          sr.Previous_Responses__c = '';            
          if (countMap.containsKey(rid)) {
            sr.Add_Info__c = '' + countMap.get(rid);
          } else {
            sr.Add_Info__c = '0.0';
          }
          
          if (collectorMap.containsKey(rid)) {
            sr.Collected_By__c = collectorMap.get(rid);             
          }

          if (dateMap.containsKey(rid)) {
            sr.Collected_Datetime__c = dateMap.get(rid);
          }
        
          if (srMap.containsKey(rid)) {        
            if ( oldCount != countMap.get(rid)) {
              //only update if counts change
              srMap.remove(rid);
              srMap.put(rid, sr);    
            }
          } else {
            insertSrList.add(sr);
          }
        }
        //Alt Survey Responses
        System.debug('construct SRs for Alt persons. altKeySet size = ' + altKeySet.size());
        for (String altKey: altKeySet) { 
          System.debug('altKey for SR = ' + altKey);
          Recruit__c r = altPersonMap.get(altKey);
          if (r == null) {
            r = oldAltMap.get(altKey);
          }
          if (r != null) {
            Survey_Response__c sr = new Survey_Response__c();

            if (altSrMap.containsKey(altKey)) {
              sr = altSrMap.get(altKey);
            } else {
              sr.Survey_Question__c = sqid;
              sr.Response_Value__c = 'yes';
              sr.Alt_First_Name__c =  r.Alt_First_Name__c;
              sr.Alt_Middle_Name__c =  r.Alt_Middle_Name__c;
              sr.Alt_Last_Name__c =  r.Alt_Last_Name__c;
              sr.Alt_Employer__c =  r.Alt_Employer__c;                              
              sr.Alt_Person_Type__c = r.Alt_Person_Type__c;                              
            }
            sr.Previous_Responses__c = '';            
            sr.Add_Info__c = '' + altCountMap.get(altKey);
            if (altCollectorMap.containsKey(altKey)) {
                 sr.Collected_By__c = altCollectorMap.get(altKey);             
            }

            if (altDateMap.containsKey(altKey)) {
              sr.Collected_Datetime__c = altDateMap.get(altKey);
            }

            if (sr.Alt_Employer__c == null && r != null && emNameMap.containsKey(r.Employer_Name__c)) {
              sr.Alt_Employer__c = emNameMap.get(r.Employer_Name__c).Id;
            }
            if (sr.Alt_Employer__c == null) {
              sr.Alt_Employer__c = defaultEmployer.Id;
            }
            if (sr.Alt_Person_Type__c == null) {
              sr.Alt_Person_Type__c = 'Other';
            }
            
            if (altSrMap.containsKey(altKey)) {        
                altSrMap.remove(altKey);
                altSrMap.put(altKey, sr);    
            } else {
                //sr.Comments__c = 'No Key Found = _' + altKey + '_ vs debug key = _' + debugSrKey + '_ alt em id=' + debugAltEmId + '_ sr list size = ' + srList.size() + '; sqlist = ' + sqList.size();
                if (r.Total_Shift__c > 0.0) {

                  insertSrList.add(sr);
                }
            }

          }
        }      
      
        if (srMap.size() > 0) {
          update srMap.values();
        }
        if (altSrMap.size() > 0) {
          update altSrMap.values();
        }      
        if (insertSrList.size() > 0) {
          insert insertSrList;
        }
      } catch (Exception e) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<User> sysAdmins = [ select Email from User where Profile.Name = 'System Administrator' and IsActive = true ];
        List<String> sysAdminEmails = new List<String>();
        for (User u: sysAdmins ) {
          sysAdminEmails.add(u.Email);
        }
        //String[] toAddresses = new String[] sysAdminEmails };
        mail.setToAddresses(sysAdminEmails );
        mail.setSubject('Recruit to Survey Response Exception For Recruit - ' + debugRecruit);
        mail.setPlainTextBody('Failure on Recruit ' + debugRecruit+ ', Employer=' + debugRecruit.Employer_Name__c + '.\n\n' + e.getStackTraceString() + '\n\n' + e.getMessage());
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
      }           
      System.debug('[Recruit to Survey Response] finish');
    }
    
    
  public static Integer cheese() {
      System.debug('[cheese] start');        
      Integer i = 0;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;                  
i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;
      i++;
      i++;
      i++;            
      i++;
      i++;
      i++;      
      return i;                                             
    }
}