src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Allowed_Responses__c</fullName>
        <defaultValue>&quot;yes&quot;</defaultValue>
        <description>The responses allowed in a Survey Response.  Separate allowed responses by a newline character.</description>
        <label>Allowed Responses</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Survey Description</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <description>Three letter Survey Code</description>
        <externalId>true</externalId>
        <label>Survey Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UHW_Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>UHW Campaign</label>
        <referenceTo>UHW_Campaign__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Alt_Employer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Alt Employer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Alt_First_Name__c</fullName>
        <label>Alt First Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alt_Last_Name__c</fullName>
        <label>Alt Last Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collected_Datetime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Collected Datetime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact Survey Response</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FID__c</fullName>
        <formula>Contact__r.FID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Value__c</fullName>
        <label>Response Value</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <formula>Survey_Question__r.Survey_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Survey Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Survey Question</description>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Survey Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/UHW_Campaign__c.object
<CustomObject>
    <label>UHW Campaign</label>
    <nameField>
        <label>UHW Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UHW Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Survey_Response_ValidateDeDupeTest.cls
@isTest(SeeAllData = true)
public class Survey_Response_ValidateDeDupeTest {

  public static testMethod void test() {
  
    UHW_Campaign__c cmp = new UHW_Campaign__c();
    cmp.name = 'Test Campaign';
    insert cmp;
  
    Account em = new Account(name='Test Employer');
    insert em;
  
    Contact c = new Contact();
    c.lastname = ('TestLast');
    c.firstName = ('TestFirst');
    c.fid__c = '9999-159990001';
    c.account = em;    
    insert c;
    
    Survey_Question__c sq = new Survey_Question__c();
    sq.Survey_Code__c = ('Z99');
    sq.name = 'Test Question';
    sq.Description__c = 'Test Description';
    sq.allowed_responses__c = '1. Leader\n2. Supporter\n3. Undecided\n4. Anti-Union\n.5. Anti-UHW\n6. Anti-UHW Leader\n9. Not Eligible';
    sq.UHW_Campaign__c = cmp.id;
    insert sq;
    
    
    Survey_Response__c sr = new Survey_Response__c();
    sr.Collected_Datetime__c = Datetime.now();
    sr.Contact__c = c.id;
    sr.Response_Value__c = '2';
    sr.Survey_Question__c = sq.id;
    insert sr;

    sr = new Survey_Response__c();
    sr.Collected_Datetime__c = Datetime.now();
    sr.Contact__c = c.id;
    sr.Response_Value__c = '1';
    sr.Survey_Question__c = sq.id;
    insert sr;
    
    sr.Response_Value__c = '3';
    update sr;
    
    
    sr = new Survey_Response__c();
    sr.Collected_Datetime__c = Datetime.now();
    sr.Alt_Last_Name__c = 'Uln';    
    sr.Alt_First_Name__c = 'Ufn';
    sr.alt_employer__c = em.id;
    sr.Response_Value__c = '1';
    sr.Survey_Question__c = sq.id;
    insert sr;
    
    System.assert(true);
  }

}