src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Allowed_Responses__c</fullName>
        <defaultValue>&quot;yes&quot;</defaultValue>
        <description>The responses allowed in a Survey Response.  Separate allowed responses by a newline character.</description>
        <label>Allowed Responses</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Survey Description</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <description>Three letter Survey Code</description>
        <externalId>true</externalId>
        <label>Survey Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Collected_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Who collected this survey response?</description>
        <label>Collected By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses (Collected By)</relationshipLabel>
        <relationshipName>Survey_Responses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact Survey Response</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hospital_System__c</fullName>
        <formula>IF (OR(ISNULL(Contact__c), ISBLANK(Contact__c)),  Alt_Employer__r.Hospital_System__c,  Contact__r.Account.Hospital_System__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hospital System</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Value__c</fullName>
        <label>Response Value</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <formula>Survey_Question__r.Survey_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Survey Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Survey Question</description>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>R{00000000}</displayFormat>
        <label>Survey Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ResponseMobileContoller.cls
public with sharing class ResponseMobileContoller {
    
  @RemoteAction
  public static List <Survey_Question__c> getSurveyQuestion(String code) {
    List <Survey_Question__c> data = [SELECT Id,Survey_Code__c,Description__c,Allowed_Responses__c FROM Survey_Question__c WHERE Survey_Code__c = :code AND IsDeleted = false];
    return data;
  }
  
  @RemoteAction
  public static List <Account> getAccountData() {
    List <Account> data = [SELECT Id, Name, Account_Group__c FROM Account WHERE Type = 'Employer' AND Active__c = 'Yes' AND (Hospital_System__c = 'DIGNITY HEALTH' OR Account_Group__c = 'Kaiser') ORDER BY Account_Group__c ASC NULLS LAST, Name ASC NULLS LAST];
    return data;
  }

  @RemoteAction
  public static List <Contact> getContactData(Id accountId, String code) {
      List <Contact> data;
      String querySoql;
      querySoql  = ' SELECT  Id, AccountId, LastName, FirstName, MobilePhone, HomePhone, Phone, DoNotCall, Shift__c, Department,';
      querySoql += ' ( SELECT Id, Response_Value__c '; 
      querySoql += '   FROM Survey_Responses__r WHERE Survey_Question__r.Survey_Code__c = \'' + code + '\' )';
      querySoql += ' FROM Contact WHERE AccountId = \'' + accountId + '\'';
      querySoql += ' ORDER BY LastName,FirstName ';
      System.debug( querySoql );
      data =  Database.query(querySoql);
      return data;
  }

  @RemoteAction
  public static String updateResponse(String userId, Id contactId, Id surveyQuestionId, Boolean attend, String respId) {  

    Survey_Response__c tmpResponse = new Survey_Response__c();
    tmpResponse.Response_Value__c  = 'yes';
    String retVal = 'ok';

    if(!String.isBlank(respId)) {
      tmpResponse.Id = respId;
      if(attend == true) {
        // ------------------------------------------------------------------------------------------- //
        // Update Response
        // ------------------------------------------------------------------------------------------- //
        try {
          Update tmpResponse;
          System.debug('Survey Response record updated. ');
        } catch(Exception e) {
          System.debug('Error updating Survey Response record. ' + e.getMessage());
          retVal = 'error';
        }
      } else {
        List<Survey_Response__c> responseArray = new List<Survey_Response__c>();
        responseArray.add(tmpResponse);
        // ------------------------------------------------------------------------------------------- //
        // Delete Response
        // ------------------------------------------------------------------------------------------- //
        Database.DeleteResult[] drList = Database.delete(responseArray, false);
        for (Database.DeleteResult dr : drList) {
          if(!dr.isSuccess()) {
            retVal = 'error';
            for(Database.Error err : dr.getErrors()) {
                System.debug('The following error has occurred.');                    
                System.debug(err.getStatusCode() + ': ' + err.getMessage());
            }
            }
          }          
      }
    } else {
      tmpResponse.Survey_Question__c = surveyQuestionId;
//      tmpResponse.Collected_By__c = userId;
      tmpResponse.Contact__c = contactId;
      // ------------------------------------------------------------------------------------------- //
      // Insert Response
      // ------------------------------------------------------------------------------------------- //
      List<Survey_Response__c> responseArray = new List<Survey_Response__c>();
      responseArray.add(tmpResponse);
      Database.SaveResult[] srList = Database.insert(responseArray, false);
      for (Database.SaveResult sr : srList) {
        if(sr.isSuccess()) {
          System.debug('Successfully inserted record.');
        }
        else {
          retVal = 'error';
            for(Database.Error err : sr.getErrors()) {
                System.debug('The following error has occurred.');                    
                System.debug(err.getStatusCode() + ': ' + err.getMessage());
            }
        }
        }
    }

    return retVal;
  }
}