src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Allowed_Responses__c</fullName>
        <defaultValue>&quot;yes&quot;</defaultValue>
        <description>The responses allowed in a Survey Response.  Separate allowed responses by a newline character.</description>
        <label>Allowed Responses</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Survey Description</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Survey_Code__c</fullName>
        <description>Three letter Survey Code</description>
        <externalId>true</externalId>
        <label>Survey Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UHW_Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>UHW Campaign</label>
        <referenceTo>UHW_Campaign__c</referenceTo>
        <relationshipLabel>Survey Questions</relationshipLabel>
        <relationshipName>Survey_Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <label>Survey Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/UHW_Campaign__c.object
<CustomObject>
    <label>UHW Campaign</label>
    <nameField>
        <label>UHW Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UHW Campaigns</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Campaign_Member_Trigger_HelperTest.cls
@isTest(SeeAllData=true)
public class Campaign_Member_Trigger_HelperTest {

  public static testMethod  void testCampaignMember() {
  
    Integer cheese = Campaign_Member_Trigger_Helper.cheese();
    
    Account em = new Account(name='Test Employer');
    insert em;
    Integer i = 0;
    
      Contact c = new Contact();
      c.LastName = ('TestLast');
      c.FirstName = ('TestFirst');
      c.FID__c = '9999-15999' + (1000 + i);
      c.Title = 'LVN';
      c.MailingPostalCode = '90022';
      c.account = em;    
      insert c;    
      System.Debug('FID = ' + c.FID__c);      

    Campaign camp = new Campaign(name='Test Campaign');
    insert camp;

    UHW_Campaign__c camp2 = new UHW_Campaign__c(name='Test Campaign');
    insert camp2;
    
    
    Survey_Question__c sq = new Survey_Question__c();
    sq.Name           = 'Test Question';
    sq.Description__c = 'Test Description';
    sq.Survey_Code__c = 'T99';
    sq.Allowed_Responses__c = 'M.Committed\nB. Confirmed\nN. Cancelled';
    sq.UHW_Campaign__c = camp2.Id;
    insert sq;
    
    CampaignMember cm = new CampaignMember();
    cm.ContactId = c.Id;
    cm.CampaignId = camp.Id;
    cm.Status = 'Sent';
    
    insert cm;
    
    System.Debug('DONE campaign member test');

    System.assert(true);
  }
  
}